### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by HADB** [jim-easterbrook/python-exiv2#11]
Python version: 3.10.8
OS: macOS Ventura 13.1, Apple M1

```
pip install exiv2
Collecting exiv2
  Downloading exiv2-0.13.2.zip (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 195.1 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Package exiv2 was not found in the pkg-config search path.
      Perhaps you should add the directory containing `exiv2.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'exiv2' found
      Command '['pkg-config', '--modversion', 'exiv2']' returned non-zero exit status 1.
      ERROR: No SWIG source for libexiv2 version None
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by jim-easterbrook** [comment]
pip is attempting to build python-exiv2 from source, as it didn't find a matching "binary wheel". Building from source fails as you don't have the header files for libexiv2 installed.

There is a MacOS wheel for Python 3.10 on PyPI which I would expect pip to use, but I'm not familiar enough with MacOS to know why it didn't. You could try downloading the wheel and installing it directly - then pip might say what's wrong with it.
`pip install exiv2-0.13.2-cp310-cp310-macosx_10_9_x86_64.whl`

**Comment by jim-easterbrook** [comment]
Ah, the M1 uses an Apple chip rather than Intel doesn't it? I'm currently only building wheels for Intel but might be able to do so for Apple silicon.

**Comment by jim-easterbrook** [comment]
The wheel builds use GitHub Actions. An M1 "runner" is currently in beta testing and scheduled to be available to ordinary users like me in July-September 2023.

As I need to build libexiv2 before the Python wheel I don't think cross compiling is an option.

**Comment by jim-easterbrook** [comment]
[exiv2-macos-arm64.zip](https://github.com/jim-easterbrook/python-exiv2/files/10664287/exiv2-macos-arm64.zip)
I might have managed to cross compile for arm64 on an x86_64 machine. The attached ZIP file contains a binary wheel for you to try installing. It doesn't include the internationalisation stuff as I couldn't get libexiv2 to link with libintl.

**Comment by jim-easterbrook** [comment]
Have you been able to try the new binary wheel @HADB ? I would like to know if it works.
