### ISSUE TITLE
Incorrect lens detection

### ISSUE THREAD

**Issue by divrn** [jim-easterbrook/python-exiv2#12]
_First of all, I want to thank you for your work. Great stuff!_
But there is one question.
I'm making an experiment from your example. I submit raw files from different cameras and different lenses. None of the lenses are detected correctly. Python-exiv2 0.14.1, MacOS 12.6.9, PyCharm, python 3.11.6
At first I thought it was something to do with the main library. I wanted to replace the file with the libexiv2.28.dylib version, but everything stopped working altogether. Then I wanted to try the CLI of Exiv2. But I never managed to launch it, because it started complaining about the absence of the libexiv2.27.dylib file, and I still didn’t understand where it should be placed. In the end, I got the result with the CLI version on Windows. There the optics are determined correctly.

```
import exiv2

def main():

    image = exiv2.ImageFactory.open("/Users/test/Desktop/_0754.NEF")
    image.readMetadata()
    exifData = image.exifData()

    for name in ('Exif.Nikon3.ColorSpace', 'lensName', 'serialNumber', 'shutterSpeedValue'):
        if hasattr(exiv2, name):
            datum = getattr(exiv2, name)(exifData)
            if datum:
                print('{:18s}: {:30s}: {:s}'.format(
                    name, datum.key(), datum._print()))
            else:
                print(name)
```
Output:
> lensName          : Exif.NikonLd3.LensIDNumber    : Nikon AF-S Nikkor 24-120mm f/4G ED VR

It should be like this: AF-S Nikkor 24-70mm f/2.8E ED VR
[Link to file](https://drive.google.com/file/d/1mBI8vWGx1upFeWmYrE-pzrMUMDaTOgUp/view?usp=sharing).

Maybe it will be error-free with the new version 0.14.2 and library 28.1, but https://pypi.org/project/exiv2 doesn’t have it, and I still don’t really understand how to assemble it myself and compile the .so files.

**Comment by jim-easterbrook** [comment]
The actual data for `Exif.NikonLd3.LensIDNumber` is a single byte, which is what `datum.value()` should give you. As you've discovered, libexiv2 interprets this byte in the `_print()` method to give a string. Different versions of libexiv2 may give a different string as camera makers add new lenses and reuse one of their 256 possible values.

python-exiv2 has to be compiled and linked with one version of libexiv2, and cannot be expected to work with another version. The exiv2 team have made a lot of changes between 0.27 and 0.28, including breaking the Canon maker note stuff that I use, so I haven't yet released python-exiv2 with libexiv2 version 0.28. Version 0.27 works well enough for most purposes.

I don't fully understand what this:
```
        if hasattr(exiv2, name):
            datum = getattr(exiv2, name)(exifData)
```
is trying to achieve. I'd simply do:
```
        if name in exifData:
            datum = exifData[name]
```

**Comment by jim-easterbrook** [comment]
The `lensName`, `serialNumber`, and `shutterSpeedValue` functions are part of the "easy access" module that I don't use much, preferring to get values by tag name. The `lensName` function has a warning that may be relevant: https://exiv2.org/doc/namespaceExiv2.html#a00abed868b1cd46fdeb8ab331af246cd

**Comment by jim-easterbrook** [comment]
Some experiments.

With libexiv2 v 0.27.7
```
>>> import exiv2
>>> im = exiv2.ImageFactory.open('_DVC0754.NEF')
>>> im.readMetadata()
>>> ex = im.exifData()
>>> d = ex['Exif.NikonLd3.LensIDNumber']
>>> d.toString()
'170'
>>> str(d)
'Exif.NikonLd3.LensIDNumber: Nikon AF-S Nikkor 24-120mm f/4G ED VR'
```

With libexiv2 v 0.28.1
```
>>> import exiv2
>>> im = exiv2.ImageFactory.open('_DVC0754.NEF')
>>> im.readMetadata()
>>> ex = im.exifData()
>>> d = ex['Exif.NikonLd3.LensIDNumber']
>>> d.toString()
'170'
>>> str(d)
'Exif.NikonLd3.LensIDNumber: Nikon AF-S Nikkor 24-120mm f/4G ED VR'
```
So it's not the libexiv2 version that's responsible!

The `exiv2` program (v 0.27.5) gets a different result:
```
exiv2 -pa _DVC0754.NEF | grep -i lens
Exif.Nikon3.LensType                         Byte        1  D G VR
Exif.Nikon3.Lens                             Rational    4  24-70mm F2.8
Exif.Nikon3.LensFStops                       Undefined   4  6
Exif.NikonLd3.LensIDNumber                   Byte        1  Nikon AF-S Nikkor 24-70mm f/2.8E ED VR
Exif.NikonLd3.LensFStops                     Byte        1  F6.0
```
Building python-exiv2 with libexiv2 v 0.27.5 still gives the 24-120mm lens though.

**Comment by jim-easterbrook** [comment]
Another source of information is Phil Harvey's `exiftool` documentation. The section about lens id values says "The Nikon LensID is constructed as a Composite tag from the raw hex values of 8 other tags: LensIDNumber, LensFStops, MinFocalLength, MaxFocalLength, MaxApertureAtMinFocal, MaxApertureAtMaxFocal, MCUVersion and LensType, in that order."
https://exiftool.org/TagNames/Nikon.html

The `Exif.NikonLd3.LensIDNumber` value 170 (AA in hex) can be any of the following lenses:
```
'AA 3C 37 6E 30 30 AC 0E'	= AF-S Nikkor 24-120mm f/4G ED VR
'AA 48 37 5C 24 24 C5 0E'	= AF-S Nikkor 24-70mm f/2.8E ED VR
'AA 48 37 5C 24 24 C5 4E'	= AF-S Nikkor 24-70mm f/2.8E ED VR
'AA 48 88 A4 3C 3C D5 0E'	= AF-S Nikkor 180-400mm f/4E TC1.4 FL ED VR + 1.4x TC
'AA 48 88 A4 3C 3C D5 4E'	= AF-S Nikkor 180-400mm f/4E TC1.4 FL ED VR + 1.4x TC
```
(And maybe more?)

It seems you need to merge the information from at least `Exif.NikonLd3.LensIDNumber` and `Exif.Nikon3.Lens` to get the right answer.

**Comment by jim-easterbrook** [comment]
> The `lensName`, `serialNumber`, and `shutterSpeedValue` functions are part of the "easy access" module that I don't use much, preferring to get values by tag name. The `lensName` function has a warning that may be relevant: https://exiv2.org/doc/namespaceExiv2.html#a00abed868b1cd46fdeb8ab331af246cd

That warning is rather misleading, as the function can only return an iterator pointing to one of the Exif data values, so no name reconstruction is done. What it really means is thet the user needs to do some reconstruction based on more data than just the one key returned.

**Comment by jim-easterbrook** [comment]
I think I may have an answer. The libexiv2 `write()` function (which implements `str()` / `_print()`) has an optional metadata pointer parameter to allow access to other keys!
https://exiv2.org/doc/classExiv2_1_1Metadatum.html#ac4642ea857704bd15f401871ddce8512

I obviously need to implement this in the Python interface.

**Comment by jim-easterbrook** [comment]
It's already there! (But not for `str()`.)
```
>>> import exiv2
>>> im = exiv2.ImageFactory.open('_DVC0754.NEF')
>>> im.readMetadata()
>>> ex = im.exifData()
>>> d = ex['Exif.NikonLd3.LensIDNumber']
>>> d._print()
'Nikon AF-S Nikkor 24-120mm f/4G ED VR'
>>> d._print(ex)
'Nikon AF-S Nikkor 24-70mm f/2.8E ED VR'
```

**Comment by jim-easterbrook** [comment]
Adding it to `str()` or any of the `Exiv2::Metadatum` (or derived class) methods isn't possible as the datum doesn't have a pointer to the `Exiv2::ExifData` it belongs to. (A datum can be created on its own without belonging to any data list.)

I don't think I can make any useful change to python-exiv2, but I'll update the examples (and my own use of python-exiv2 in other projects). Thank you for drawing my attention to why exifdata can be passed to `_print()`.

**Comment by divrn** [comment]
Thanks for the help! I believe that now I will be able to extract the lens model from the raw file of _**any**_ camera and transfer it to the corresponding jpeg.

**Comment by divrn** [comment]
Thanks for the help! I believe that now I will be able to extract the lens model from the raw file of _**any**_ camera and transfer it to the corresponding jpeg.
