### ISSUE TITLE
pip install error 0.16.3

### ISSUE THREAD

**Issue by yanyingchen** [jim-easterbrook/python-exiv2#36]
Python version: 3.11
OS: linux/amd64
(Note that installing exiv2 v0.16.3 on Mac OS, Python 3.11.6 was successful.)
> ...
> [2024-07-19T21:16:58.876Z] #9 1.994 Collecting exiv2==0.16.3
> [2024-07-19T21:16:58.876Z] #9 2.004  Downloading exiv2-0.16.3.tar.gz (2.3 MB)
> [2024-07-19T21:16:59.131Z] #9 2.026   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 121.0 MB/s eta 0:00:00
> [2024-07-19T21:16:59.131Z] #9 2.191  Installing build dependencies: started
> [2024-07-19T21:17:01.018Z] #9 3.892  Installing build dependencies: finished with status ‘done’
> [2024-07-19T21:17:01.018Z] #9 3.893  Getting requirements to build wheel: started
> [2024-07-19T21:17:01.018Z] #9 4.026  Getting requirements to build wheel: finished with status ‘error’
> [2024-07-19T21:17:01.018Z] #9 4.030  error: subprocess-exited-with-error
> [2024-07-19T21:17:01.018Z] #9 4.030
> [2024-07-19T21:17:01.018Z] #9 4.030  × Getting requirements to build wheel did not run successfully.
> [2024-07-19T21:17:01.018Z] #9 4.030  │ exit code: 1
> [2024-07-19T21:17:01.018Z] #9 4.030  ╰─> [2 lines of output]
> [2024-07-19T21:17:01.018Z] #9 4.030    [Errno 2] No such file or directory: ‘pkg-config’
> [2024-07-19T21:17:01.018Z] #9 4.030    ERROR: No SWIG source for libexiv2 version None
> [2024-07-19T21:17:01.018Z] #9 4.030    [end of output]
> [2024-07-19T21:17:01.018Z] #9 4.030
> [2024-07-19T21:17:01.018Z] #9 4.030  note: This error originates from a subprocess, and is likely not a problem with pip.
> [2024-07-19T21:17:01.018Z] #9 4.031 error: subprocess-exited-with-error
> [2024-07-19T21:17:01.018Z] #9 4.031
> [2024-07-19T21:17:01.018Z] #9 4.031 × Getting requirements to build wheel did not run successfully.
> [2024-07-19T21:17:01.018Z] #9 4.031 │ exit code: 1
> [2024-07-19T21:17:01.018Z] #9 4.031 ╰─> See above for output.
> [2024-07-19T21:17:01.018Z] #9 4.031
> [2024-07-19T21:17:01.018Z] #9 4.031 note: This error originates from a subprocess, and is likely not a problem with pip.
> ...

**Comment by yanyingchen** [comment]
Well, "pip install" failed on "OS: linux/amd64" for various exiv2 versions but not just the v0.16.3. 
The following pip install all failed: 

> pip install exiv2==0.16.3
> pip install exiv2==0.16.2
> pip install exiv2==0.16.1
> pip install exiv2==0.16.0
> pip install exiv2==0.15.0

**Comment by yanyingchen** [comment]
I realized this was becuase my machine did not have the compatible glibc version.

**Comment by jim-easterbrook** [comment]
Binary wheels for the `python-exiv2` dependency are only available for a limited range of system architectures. For other architectures you need to compile the package during installation, which requires the "header" files for `libexiv2`. These should be installable with your system package manager, and will probably have a name like `exiv2-dev`.
