### ISSUE TITLE
read data from a stream

### ISSUE THREAD

**Issue by kif** [jim-easterbrook/python-exiv2#5]
Hi,
I am working on embedded device and I wish to treat metadata from streams in memory (typically io.BytesIO containing the content of a JPEG file). I wonder if your library supports this feature or if you see a way to do something like this ?
Thanks for your input,

Jerome

**Comment by jim-easterbrook** [comment]
`exiv2.ImageFactory.open` can read data from any Python object that uses the Python buffer interface to expose a readable contiguous buffer, such as `bytes` or `bytearray`.

`exiv2.Image.io` returns a Python buffer object pointing at the image data which can be converted (without copying) to a Python `bytes` object or passed to any Python function that accepts a buffer, such as `File.write`.

https://github.com/jim-easterbrook/python-exiv2#buffer-interface

**Comment by kif** [comment]
Hi Jim,
Thanks for the answer, With your help, I managed to get it working.
For now I still have a copy of the memory object but it should be feasible without.

**Comment by jim-easterbrook** [comment]
In the next release (v0.13.0) the `BasicIo` object returned by `exiv2.Image.io()` has a working `mmap()` method that returns a Python `memoryview` (https://docs.python.org/3/library/stdtypes.html#memoryview) object. The buffer interface to `BasicIo` will be deprecated and eventually withdrawn.

**Comment by jim-easterbrook** [comment]
I've just released v0.13.0. `mmap()` now returns an object that has the buffer interface. This can be used directly by many things that expect `bytes`, or a `memoryview` can be used to give copy-free access to the data.
