### ISSUE TITLE
Exiv2 iterator issue

### ISSUE THREAD

**Issue by tester0077** [jim-easterbrook/python-exiv2#7]
I am running the current version 0.12.0 of exiv2 on Mint for a jpg file with various metadata already added.
For now, I just wanted to list all the metadata found in an image.
Hence I am using the iterator shown in one of the example and my basic stripped down code looks like

```
image = exiv2.ImageFactory.open(image)
image.readMetadata()
data = image.exifData()
if ( data.empty()):
	   ,,, handle case of no exifdata
else:
	print( "type"  + str(type( data)) )
	b = data.begin()
	e = data.end()
	while b != e:
		nExiv2 += 1
		curTag = b.key()
		curValue = b.value()	
		..... display any EXIF data found
next( b )
```
The problem I am seeing is that the first data item in each group - EXIF, IPTC & XMP seems to be reported twice - not what I expected.

FWIW, I am quite new to Python, though I am reasonably familiar with metadata and Exiv2.
Perhaps I should use another way to iterate over all data, but I picked this as a newb and am quite willing to change if necessary. Still curious though :-)

**Comment by jim-easterbrook** [comment]
I assume the lack of indentation of `next(b)` is an error not present in your actual code.

I can't think of a reason why just the first tag should get repeated. I'll do some tests of my own and see if I can reproduce the problem. Note that IPTC data can be repeated - it's how you have more than one keyword - so it's possible your file actually has duplicate data.

The more pythonic, and slightly more efficient, way to iterate over the data is as follows.
```
image = exiv2.ImageFactory.open(image)
image.readMetadata()
data = image.exifData()
if not data:
	... handle case of no exifdata
else:
	print( "type"  + str(type( data)) )
for datum in data:
	nExiv2 += 1
	curTag = datum.key()
	curValue = datum.value()	
	..... display any EXIF data found
```

**Comment by jim-easterbrook** [comment]
I've just tried a loop similar to yours and yes, the first datum is repeated!

**Comment by jim-easterbrook** [comment]
If you print the value of `b` directly it's correct, but accessing it via `b.key()` and `b.value()` gets the previous data. There's something very odd going on.
```
b = data.begin()
e = data.end()
nExiv2 = 0
while b != e:
    nExiv2 += 1
    curTag = b.key()
    curValue = b.value()
    print(b, curTag, curValue)
    next(b)
    if nExiv2 >= 5:
        break
```
Gives me this:
```
iterator<Exif.Image.ProcessingSoftware: Photini editor v2022.11.0> Exif.Image.ProcessingSoftware Photini editor v2022.11.0
iterator<Exif.Image.ImageDescription: Flower gardens on the Rue d'Alsace-Lorraine. // Château-Gontier, France> Exif.Image.ProcessingSoftware Photini editor v2022.11.0
iterator<Exif.Image.Make: Canon> Exif.Image.ImageDescription Flower gardens on the Rue d'Alsace-Lorraine. // Château-Gontier, France
iterator<Exif.Image.Model: Canon PowerShot A1100 IS> Exif.Image.Make Canon
iterator<Exif.Image.Orientation: top, left> Exif.Image.Model Canon PowerShot A1100 IS
```

**Comment by tester0077** [comment]
Thank you for the quick response ... much appreciated.
and, Yes, the indentation of the code I posted is incorrect as you realized.

As you mentioned, I have also found that the Keywords in the metadata end up as separate items and for the time being I had to ignore those results until I figure out a way to handle them.
This does raise another question, though.
Other similar fields/tags do seem to be handled without duplication, such as PersonInImage.

How can I find out what sort of data structure the returned object represents and handle the data accordingly?
Among others, I am specifically interested in lang-alt tags
I am just learning Python, from a C++ background, so many operations are very mysterious and, without examples, hard to get a handle on.

**Comment by jim-easterbrook** [comment]
libexiv2 has static classes with details of the known data types, e.g. Exiv2::XmpProperties https://exiv2.org/doc/classExiv2_1_1XmpProperties.html

If you have a datum object you can call its `typeId()` or `typeName()` methods to get the data type. The repeatability of IPTC data is stored in `exiv2.IptcDataSets.dataSetRepeatable`.

You might be interested in how I use exiv2 in one of my other projects: https://github.com/jim-easterbrook/Photini/blob/main/src/photini/exiv2.py This is not a definitive way to do things, but it's what works for me.

To get back to the original problem, I'm amazed my python-exiv2 iterators ever worked properly. I don't think I was lying when I wrote the README but my attempt to unify the C++ and Python style iterators is doomed. I hadn't properly understood that a Python iterator doesn't itself point to the data, it returns the first and subsequent data objects when its `next()` method is called. I'll get a new release of python-exiv2 out this week that does both styles of iterators properly. Calling `next(b)` on a C++ style iterator (as returned by `data.begin()`) is a nonsense to be replaced by something like `b += 1`.

**Comment by jim-easterbrook** [comment]
I think I introduced this bug in version 0.10.0, in an attempt to make the iterators simpler and safer. I now understand how it's supposed to work, and it should be easy enough to fix without any major changes.

**Comment by jim-easterbrook** [comment]
I've just released v0.12.1 which should fix this.

Thank you for reporting the bug.

**Comment by jim-easterbrook** [comment]
I've now added a simple unit test (my first foray into Python testing) to detect any future reintroduction of this bug.

**Comment by tester0077** [comment]
Thank you :-)
The update worked  - still a lot to learn with this Python stuff

As for the initialize / terminate stuff - once upon a time, during the time when Robin Mills was still active, I had been using Exiv2 as a C++ library, and one of the issues I recall being worked on was work to remove the need for that bracketing pair. AFAIR, it was successfully done, but I have not been able to find a reference in the changelogs I managed to find..
In any case, my code works as expected without these call, so I will keep on without using these call. But I wanted to make sure that this was not something I just missed tripping over.
